name: ci-build

on:
  push:
    branches:
      - main
      - 'rel/v*'
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          10.0.x
    - name: Install dependencies
      run: dotnet restore UnlockedData.Chartist.Blazor.sln
    - name: ngbv set version
      uses: dotnet/nbgv@v0.4
      with:
        setAllVars: true
    - run: echo "NBGV_SemVer2 $NBGV_SemVer2"
    - name: Build
      run: dotnet build UnlockedData.Chartist.Blazor.sln --configuration Release --no-restore
    - name: Unit Tests
      run: dotnet test UnlockedData.Chartist.Blazor.sln --no-restore --verbosity normal
    - name: Create Package Dir
      run: mkdir ${{ github.workspace }}/package
    - name: Pack
      run: dotnet pack UnlockedData.Chartist.Blazor.sln --no-build -c Release --output "${{ github.workspace }}/package"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget
        path: ${{ github.workspace }}/package
    - name: Push to NuGet
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/rel/v')
      run: dotnet nuget push "${{ github.workspace }}/package/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate